// ================================================================
// model.h — TFLite INT8 Health Classifier (18 KB)
// Generated by Edge Impulse EON Compiler for ESP32-S3
// 
// TO REPLACE THIS PLACEHOLDER:
// 1. Go to your Edge Impulse project
// 2. Deployment > TensorFlow Lite (INT8 quantised)
// 3. Download and copy the model.h content here
// ================================================================

#pragma once
#include <cstdint>

// Placeholder: replace with actual model bytes from Edge Impulse export
const uint8_t health_model_tflite[] = {
    0x18, 0x00, 0x00, 0x00, // placeholder header
    // ... actual model bytes go here after Edge Impulse export
};
const int health_model_tflite_len = sizeof(health_model_tflite);
